import './style.css';
const SITE='https://merahi-village.github.io', BLOG='https://merahivillage.blogspot.com';
const WEATHER='https://api.open-meteo.com/v1/forecast?latitude=26.0720443&longitude=84.4049278&current=temperature_2m,relative_humidity_2m,apparent_temperature,wind_speed_10m,pressure_msl,precipitation&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code&timezone=Asia%2FKolkata&forecast_days=7';
const app=document.querySelector('#app'); const state={weather:null,places:[],articles:[],active:'home'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const wicon=c=>[0,1].includes(c)?'☀️':[2,3].includes(c)?'⛅':[45,48].includes(c)?'🌫️':[51,53,55,56,57].includes(c)?'🌦️':[61,63,65,66,67,80,81,82].includes(c)?'🌧️':[71,73,75,77,85,86].includes(c)?'❄️':[95,96,99].includes(c)?'⛈️':'🌤️';
const fdate=s=>new Intl.DateTimeFormat('hi-IN',{day:'numeric',month:'short'}).format(new Date(s+'T00:00:00'));
async function weather(){try{state.weather=await (await fetch(WEATHER,{cache:'no-store'})).json()}catch{}}
async function places(){try{const h=await (await fetch(SITE+'/places.html',{cache:'no-store'})).text(),d=new DOMParser().parseFromString(h,'text/html'),a=[...d.querySelectorAll('main a,article,.card,.place-card')].map(x=>(x.textContent||'').replace(/\s+/g,' ').trim()).filter(x=>/Chhath Ghat|Shiv Mandir|Ram Janki|Brahma Baba|Primary School/i.test(x)&&x.length<500);state.places=[...new Set(a)].slice(0,6)}catch{state.places=['🌅 Chhath Ghat','🛕 Shiv Mandir','🛕 Ram Janki Durga Shiv Mandir','🌳 Brahma Baba','🏫 Primary School']}}
async function articles(){try{const j=await (await fetch(BLOG+'/feeds/posts/default?alt=json&max-results=6',{cache:'no-store'})).json();state.articles=(j.feed?.entry||[]).map(e=>({title:e.title?.$t||'Merahi Blog',link:(e.link||[]).find(x=>x.rel==='alternate')?.href||BLOG,date:e.published?.$t?new Date(e.published.$t):null}))}catch{}}
function weatherCard(){const c=state.weather?.current;if(!c)return '<div class="loading">मौसम डेटा उपलब्ध नहीं है। ऊपर Weather देखें।</div>';return `<div class="weather-main"><div><span class="weather-icon">${wicon(state.weather.daily.weather_code[0])}</span><b>${Math.round(c.temperature_2m)}°</b></div><span>${Math.round(c.apparent_temperature)}° महसूस • ${Math.round(c.relative_humidity_2m)}% नमी</span></div><div class="weather-stats"><span>💨 ${Math.round(c.wind_speed_10m)} km/h</span><span>🧭 ${Math.round(c.pressure_msl)} hPa</span><span>🌧️ ${c.precipitation} mm</span></div>`}
function shell(body){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><img src="${SITE}/images/logo_merahi.webp"><div><strong>mOne</strong><small>खेती • प्रकृति • गाँव</small></div></div><button class="icon-btn" onclick="openSite()">↗</button></header>${body}<nav class="bottom"><button onclick="showTab('home')">⌂<small>Home</small></button><button onclick="showTab('kheti')">🌾<small>Kheti</small></button><button onclick="showTab('green')">🌱<small>Green</small></button><button onclick="showTab('blog')">📰<small>Blog</small></button><button onclick="showTab('village')">☰<small>More</small></button></nav></div>`}
function home(){state.active='home';shell(`<main><section class="hero"><div class="hero-copy"><span class="eyebrow">🌱 OUR VILLAGE • OUR FUTURE</span><h1>खेती और हरियाली<br>एक साथ बढ़ाएँ</h1><p>Merahi Village की खेती, मौसम, हरित जीवन और गाँव की जानकारी — एक ही जगह।</p><button class="primary" onclick="showTab('kheti')">🌾 खेती शुरू करें</button></div><div class="hero-leaf">🌾</div></section><section class="section"><div class="section-head"><h2>आज का मौसम</h2><button onclick="showTab('weather')">पूरा देखें →</button></div><div class="weather-card">${weatherCard()}</div></section><section class="quick-grid"><button onclick="showTab('kheti')"><span>🌾</span><b>खेती</b><small>फसल और सलाह</small></button><button onclick="showTab('green')"><span>🌱</span><b>Go Green</b><small>प्रकृति बचाएँ</small></button><button onclick="showTab('village')"><span>🏡</span><b>Merahi</b><small>गाँव की जानकारी</small></button><button onclick="showTab('blog')"><span>📰</span><b>Blog</b><small>नई जानकारी</small></button></section><section class="section"><div class="section-head"><h2>🌿 आज का Green Tip</h2></div><div class="tip"><strong>घर से शुरुआत करें</strong><p>Kitchen waste को अलग करके compost बनाना शुरू करें। इससे कचरा कम होता है और पौधों के लिए जैविक खाद मिलती है।</p></div></section><section class="section"><div class="section-head"><h2>📍 Merahi में देखें</h2><button onclick="showTab('village')">सभी →</button></div><div class="place-row">${state.places.slice(0,5).map(p=>`<div class="place">${esc(p.slice(0,90))}</div>`).join('')}</div></section></main>`)}
function page(title,icon,body){shell(`<header class="subbar"><button class="back" onclick="showTab('home')">‹</button><div>${icon} ${title}</div><button class="icon-btn" onclick="openSite()">↗</button></header><main class="page">${body}</main>`)}
window.showTab=tab=>{state.active=tab;if(tab==='home')return home();if(tab==='weather')return page('मौसम','🌦️',`<div class="weather-card large">${weatherCard()}</div><h2>अगले 7 दिन</h2><div class="forecast">${(state.weather?.daily?.time||[]).map((d,i)=>`<div><b>${fdate(d)}</b><span>${wicon(state.weather.daily.weather_code[i])}</span><strong>${Math.round(state.weather.daily.temperature_2m_max[i])}° / ${Math.round(state.weather.daily.temperature_2m_min[i])}°</strong><small>बारिश ${state.weather.daily.precipitation_probability_max[i]}%</small></div>`).join('')}</div><a class="wide-link" href="${SITE}/weather.html">Merahi Weather Dashboard खोलें ↗</a>`);if(tab==='kheti')return page('खेती','🌾',`<div class="intro-card"><h2>Merahi की खेती</h2><p>Merahi में गेहूँ, धान और seasonal vegetables की खेती होती है। Organic methods को भी बढ़ावा दिया जा सकता है।</p></div><div class="topic-grid"><div>🌾<b>धान</b><small>मौसम और जल प्रबंधन</small></div><div>🌾<b>गेहूँ</b><small>बुवाई और सिंचाई</small></div><div>🥬<b>सब्जियाँ</b><small>Seasonal crops</small></div><div>🪱<b>जैविक खेती</b><small>Compost & manure</small></div></div><div class="notice">💡 अगला चरण: बीज, खाद, लागत और खेत-area calculators।</div>`);if(tab==='green')return page('Go Green','🌱',`<div class="green-banner"><span>🌳</span><h2>हरियाली बढ़ाएँ</h2><p>छोटे कदम मिलकर साफ और हरा गाँव बना सकते हैं।</p></div><div class="list"><div>🌳 <b>पेड़ लगाएँ</b><small>स्थानीय और उपयोगी पौधों को बढ़ावा दें।</small></div><div>💧 <b>पानी बचाएँ</b><small>Rainwater harvesting और leak control अपनाएँ।</small></div><div>♻️ <b>कचरा अलग करें</b><small>Wet और dry waste को अलग रखें।</small></div><div>🌾 <b>पराली न जलाएँ</b><small>Crop residue का compost या अन्य उपयोग करें।</small></div><div>☀️ <b>सौर ऊर्जा</b><small>जहाँ संभव हो clean energy का उपयोग बढ़ाएँ।</small></div></div>`);if(tab==='blog')return page('Latest Blog','📰',`<p class="muted">Blogger feed से posts अपने-आप लाने की कोशिश की जाती है।</p><div class="articles">${state.articles.length?state.articles.map(a=>`<a href="${esc(a.link)}" target="_blank"><b>${esc(a.title)}</b><small>${a.date?a.date.toLocaleDateString('hi-IN'):''}</small><span>पढ़ें ↗</span></a>`).join(''):'<div class="empty">Blog feed अभी उपलब्ध नहीं है। नीचे website खोलें।</div>'}</div><a class="wide-link" href="${BLOG}" target="_blank">Merahi Blog खोलें ↗</a>`);return page('Merahi Village','🏡',`<div class="intro-card"><h2>मेरही — हमारा गाँव</h2><p>Hasanpura Block, Siwan, Bihar. यह एक कृषि-प्रधान ग्रामीण समुदाय है।</p></div><div class="stats"><div><b>~1,829</b><small>Residents</small></div><div><b>2.58 km²</b><small>Area</small></div><div><b>291</b><small>Households</small></div><div><b>63%</b><small>Literacy</small></div></div><div class="list"><a href="${SITE}/about-village.html">📖 About Village ↗</a><a href="${SITE}/places.html">📍 Explore Places ↗</a><a href="${SITE}/gallery.html">📸 Gallery ↗</a><a href="${SITE}/videos.html">🎬 Videos ↗</a><a href="${SITE}/contact-us.html">✉️ Contact ↗</a></div>`)};
window.openSite=()=>location.href=SITE;
app.innerHTML='<div class="splash">🌱<h1>mOne</h1><p>खेती • प्रकृति • गाँव</p></div>';
Promise.all([weather(),places(),articles()]).then(home);
